print('==== DESAFIO 009 ====')
valor = int(input('Digite um número para ver sua tabuada:'))
print('____________')
print(f'{valor} x 1 = {valor*1}')
print(f'{valor} x 2 = {valor*2}')
print(f'{valor} x 3 = {valor*3}')
print(f'{valor} x 4 = {valor*4}')
print(f'{valor} x 5 = {valor*5}')
print(f'{valor} x 6 = {valor*6}')
print(f'{valor} x 7 = {valor*7}')
print(f'{valor} x 8 = {valor*8}')
print(f'{valor} x 9 = {valor*9}')
print(f'{valor} x 10 = {valor*10}')
print('____________')